export MatrixComponent          from './matrix';
export DiagnosisComponent       from './diagnosis';
export CreateQuestionComponent  from './createDiagnosisQuestion/createQuestion'
export ConditionsComponent      from './conditions';
export TreatmentsComponent      from './treatments';
export EvaluationComponent      from './evaluation'
export PackagesComponent        from './packages';
export ExercisesComponent       from './exercises';
//export AchievementsComponent    from './achievements'
//export MetaControlsComponent    from './metaControls'
//export TestsComponent           from './tests'
export CreateConditionComponent  from './createConditionsQuestion/createConditionsQuestion';
export CreateTreatmentsComponent from './createTreatmentsQuestion/createTreatmentsQuestion';
export CreateEvaluationComponent from './createEvaluationQuestion/createEvaluation';
export CreatePackageComponent    from './createPackageQuestion/createPackage';
