export MatrixComponent          from './matrix';
export DiagnosisComponent       from './diagnosis';
export CreateQuestionComponent  from './createDiagnosisQuestion/createQuestion'
//export ConditionsComponent      from './conditions';
//export TreatmentsComponent      from './treatments';
export PackagesComponent        from './packages'
//export EvaluationComponent      from './evaluation'
//export MetaControlsComponent    from './metaControls'
//export AchievementsComponent    from './achievements'
//export ExercisesComponent       from './exercises'
//export TestsComponent           from './tests'
